from time import sleep, time
from tkinter import mainloop
print("Посчитай число")

numb=input("Введите числа для подсчетов: ")
res=eval(numb)
print("Ответ:",res)
sleep(1)
numb=input("ведите числа для подсчетов: ")
res=eval(numb)
print("Ответ:",res)
sleep(1)
numb=input("ведите числа для подсчетов: ")
res=eval(numb)
print("Ответ:",res)
sleep(1)
numb=input("ведите числа для подсчетов: ")
res=eval(numb)
print("Ответ:",res)
sleep(1)
numb=input("ведите числа для подсчетов: ")
res=eval(numb)
print("Ответ:",res)
sleep(1)
numb=input("ведите числа для подсчетов: ")
res=eval(numb)
print("Ответ:",res)
sleep(1)
numb=input("ведите числа для подсчетов: ")
res=eval(numb)
print("Ответ:",res)
sleep(1)
numb=input("ведите числа для подсчетов: ")
res=eval(numb)
print("Ответ:",res)
sleep(1)
numb=input("ведите числа для подсчетов: ")
res=eval(numb)
print("Ответ:",res)
sleep(1)
numb=input("ведите числа для подсчетов: ")
res=eval(numb)
print("Ответ:",res)
sleep(1)
numb=input("ведите числа для подсчетов: ")
res=eval(numb)
print("Ответ:",res)
sleep(1)
numb=input("ведите числа для подсчетов: ")
res=eval(numb)
print("Ответ:",res)
sleep(1)
numb=input("ведите числа для подсчетов: ")
res=eval(numb)
print("Ответ:",res)
sleep(1)
numb=input("ведите числа для подсчетов: ")
res=eval(numb)
print("Ответ:",res)
sleep(1)
numb=input("ведите числа для подсчетов: ")
res=eval(numb)
print("Ответ:",res)
sleep(1)
numb=input("ведите числа для подсчетов: ")
res=eval(numb)
print("Ответ:",res)
sleep(1)
numb=input("ведите числа для подсчетов: ")
res=eval(numb)
print("Ответ:",res)
sleep(1)
numb=input("ведите числа для подсчетов: ")
res=eval(numb)
print("Ответ:",res)
sleep(1)
numb=input("ведите числа для подсчетов: ")
res=eval(numb)
print("Ответ:",res)
sleep(1)
numb=input("ведите числа для подсчетов: ")
res=eval(numb)
print("Ответ:",res)
sleep(1)
numb=input("ведите числа для подсчетов: ")
res=eval(numb)
print("Ответ:",res)
sleep(1)
numb=input("ведите числа для подсчетов: ")
res=eval(numb)
print("Ответ:",res)
sleep(1)
numb=input("ведите числа для подсчетов: ")
res=eval(numb)
print("Ответ:",res)
mainloop()